services:
  app:
    build:
      target: base
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 8.8.4.4
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./workspace:/app/workspace
      - ./output:/app/output
    stdin_open: true
    tty: true
